apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helm-second-simple-flask-app-ingress
  namespace: dev # Replace with the namespace where your Flask app is deployed
spec:
  rules:
  - host: flask.notjustdevops.com  # Replace with your desired hostname
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ include "helm-second-simple-flask-app.fullname" . }}  # Correct Helm template syntax
            port:
              number: 80  # Replace with the port number your Flask app is listening on (5000 in your case)
