apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000  # Use port 5000 of the backend pod
    name: flask
  selector:
    app: {{ .Values.appName }}
    tier: frontend
  type: LoadBalancer
