apiVersion: v1
kind: Service
metadata:
  name: helm-second-simple-flask-app
spec:
  selector:
    app: helm-second-simple-flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP